aarch64: Fix lowering amounts for shifts
bytecodealliance/wasmtime pull request #3074
Opened 2021-07-10 11:33 UTC by afonso360

This PR addresses two issues:
* A panic when shifting any non i128 type by i128 amounts (#3064)
* Wrong results when lowering shifts with small types (i8, i16)

In these types when shifting for amounts larger than the size of the
type, we would not get the wrapping behaviour that we see on i32 and i64.
This is because in these larger types, the wrapping behaviour is automatically
implemented by using the appropriate instruction, however we do not
have i8 and i16 specific instructions, so we have to manually wrap
the shift amount with an AND instruction.

This issue is also found on x86_64 and s390x, and a separate issue will
be filed for those.

Closes #3064

2021-07-14 13:47 UTC, akirilov-arm requested changes

2021-07-14 13:47 UTC, akirilov-arm commented on cranelift/codegen/src/isa/aarch64/lower_inst.rs
> +            fn lower_shift_amt<C: LowerCtx<I = Inst>>(
Could you extract this helper function to `lower.rs`?

2021-07-14 13:47 UTC, akirilov-arm commented on cranelift/codegen/src/isa/aarch64/lower_inst.rs
> +                        let tmp = ctx.alloc_tmp(I32).only_reg().unwrap();
Another potential optimization here is to use the shift destination register instead of a temporary one.

2021-07-15 23:15 UTC, akirilov-arm approved these changes

2021-07-16 11:11 UTC, afonso360 commented
Thanks for reviewing @akirilov-arm!

2021-07-16 11:13 UTC, akirilov-arm commented
No problem; once the pull request passes the tests, it should be ready for merging.

2021-07-16 11:35 UTC, afonso360 commented
These look like spurious failures to me. It looks like crates.io is not having a great time right now. My other PR is also failing due to the same reason.

Retrying CI later may work out better

2021-07-16 18:20 UTC, akirilov-arm commented
Yes, that's true - all active PRs are failing right now with the same cause, including one of mine and another one.

2021-07-16 21:08 UTC, merged