Docs: Created the Wasmtime Markdown Parser Example
bytecodealliance/wasmtime pull request #3193
Opened 2021-08-16 22:19 UTC by torch2424

This implements the example that is missing on the Wasmtime Docs: https://docs.wasmtime.dev/examples-markdown.html

It uses the same [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark) library I've seen used across many Rust/Wasm markdown examples (for example: https://github.com/tschneidereit/pulldown-cmark-wasm )

The example is also inspired by the WASI example on the WasmByExample website: https://wasmbyexample.dev/examples/wasi-hello-world/wasi-hello-world.rust.en-us.html

# Example

```
torch2424 at torch2424-XPS-13-7390 in ~/Source/wasmtime/docs/rust_wasi_markdown_parser on torch2424/rust-wasi-markdown-parser-example
$ cargo build --target wasm32-wasi    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
torch2424 at torch2424-XPS-13-7390 in ~/Source/wasmtime/docs/rust_wasi_markdown_parser on torch2424/rust-wasi-markdown-parser-example
$ wasmtime --mapdir .::. target/wasm32-wasi/debug/rust_wasi_markdown_parser.wasm ./example_markdown.md 
<h1>Hello!</h1>
<p>I am example markdown for this demo!</p>

torch2424 at torch2424-XPS-13-7390 in ~/Source/wasmtime/docs/rust_wasi_markdown_parser on torch2424/rust-wasi-markdown-parser-example
$ 
```

2021-08-17 09:18 UTC, tschneidereit requested changes
Thank you, it's great to have this as an example!

I left some comments and suggestions below, but they should be pretty quick to address, I think, and then we can land this :)

2021-08-17 09:18 UTC, tschneidereit commented on docs/rust_wasi_markdown_parser/src/main.rs
> +    let args: Vec<String> = env::args().collect();
I think it'd be nice to use one of the existing arg parsing crates here, to get good help messages, etc. Using StructOpt, that could look roughly like this:

```rust

#[derive(StructOpt)]
pub struct Options {
    /// The markdown file to render
    #[structopt(parse(from_os_str))]
    filename: PathBuf,
}


fn main() {
    let options = Options::from_args();
   // and then use `options.filename`
  // [..]
}
```

2021-08-17 09:18 UTC, tschneidereit commented on docs/rust_wasi_markdown_parser/src/main.rs
> +    let result = format(contents);
Nit: I think `render_markdown` might be a better name than `format`

2021-08-17 09:18 UTC, tschneidereit commented on docs/rust_wasi_markdown_parser/src/main.rs
> +// Create a function for converting a markdown string, into an HTML string
I think I'd slightly prefer simply dropping this comment, at least with the name change suggested above.

2021-08-17 09:18 UTC, tschneidereit commented on docs/rust_wasi_markdown_parser/.gitignore
> +debug/
I'm a bit confused by the need of all these—you really should only need to exclude `target`, which contains all of these.

I also think all the others below aren't really needed for this example, so perhaps just make this `.gitignore` file match what `cargo new` creates by default—i.e. only include `/target`?

2021-08-17 09:18 UTC, tschneidereit commented on docs/examples-markdown.md
> +To grant the capability to write in a directory using the Wasmtime CLI, we need to use the --mapdir flag. --mapdir will allow us to map the current directory on the guest's (our program's compiled WA
I think for this example `--dir` would also work, and be a bit easier to follow along with.

2021-08-18 00:41 UTC, torch2424 commented
@tschneidereit Made the requested changes, this should be good to go! 😄 🎉

2021-08-18 07:50 UTC, tschneidereit approved these changes
Excellent, thank you! I suggested a tiny additional change will I'll just fold in and land with your changes.

2021-08-18 07:50 UTC, tschneidereit commented on docs/examples-markdown.md
> +To grant the capability to read in a directory using the Wasmtime CLI, we need to use the --dir flag. --dir will instruct wasmtime to allow our wasm module to preopen, and read files in the passed di
```suggestion
To grant the capability to read in a directory using the Wasmtime CLI, we need to use the --dir flag. --dir will instruct wasmtime to make the passed directory available to access files from. (You can also `--mapdir GUEST_DIRECTORY::HOST_DIRECTORY` to make it available under a different path inside the content.) For example:
```

2021-08-18 09:06 UTC, tschneidereit reviewed
I think the CI failure might be because the shell script blocks aren't annotated as such? I'll add those annotations (and fix a couple minor issues I noticed while doing so) and see what that does.

2021-08-18 09:06 UTC, tschneidereit commented on docs/examples-markdown.md
> +```
```suggestion
```bash
```

2021-08-18 09:06 UTC, tschneidereit commented on docs/examples-markdown.md
> +```
```suggestion
```bash
```

2021-08-18 09:06 UTC, tschneidereit commented on docs/examples-markdown.md
> +```
```suggestion
```bash
```

2021-08-18 09:06 UTC, tschneidereit commented on docs/examples-markdown.md
> +```
```suggestion
```bash
```

2021-08-18 09:06 UTC, tschneidereit commented on docs/examples-markdown.md
> +demouser at demo in ~ $ wasmtime --dir . target/wasm32-wasi/debug/rust_wasi_markdown_parser.wasm -- ./example_markdown.md
```suggestion
```bash
$ wasmtime --dir . target/wasm32-wasi/debug/rust_wasi_markdown_parser.wasm -- ./example_markdown.md 
```

2021-08-18 09:06 UTC, tschneidereit commented on docs/examples-markdown.md
> +
```suggestion
```

2021-08-18 09:22 UTC, tschneidereit commented
Hmm, this is still failing, but now with a different issue, which I'm not sure how to resolve.

2021-08-18 14:08 UTC, alexcrichton commented
I'd probably just tag the code example as `ignore` if it's already built elsewhere since it's probably too much of a pain to get it working otherwise with `mdbook --test`

2021-08-18 18:12 UTC, torch2424 commented
@tschneidereit Just wanted to shoutout and say, thanks for the comments and fixes on them! 😄 And thanks for the suggestion @alexcrichton ! 🙏🏾 😄 

I'll let @tschneidereit make the call if ignoring is the right thing to do, because I don't think I have enough context on the docs to agree or push back yet 😂

2021-08-30 14:16 UTC, alexcrichton reviewed
A few small things but otherwise 👍

2021-08-30 14:16 UTC, alexcrichton commented on docs/rust_wasi_markdown_parser/.gitignore
> +
I think this may no longer be necessary since this is part of the main workspace?

2021-08-30 14:16 UTC, alexcrichton commented on docs/rust_wasi_markdown_parser/Cargo.lock
> +[[package]]
Similar to above I think this is no longer needed?

2021-08-31 19:00 UTC, torch2424 commented
@alexcrichton I made the requested changes! Nice catch about the workspaces. I haven't worked in a Rust project this large, with multiple sub packages in a workspace, so, I'm sure I made some small errors here and there haha! 😄 

Thanks for the insight! This should be good to go! 😄

2021-09-01 17:25 UTC, alexcrichton commented
👍

2021-09-01 17:25 UTC, merged