Override component model `Lower::store_list` and `Lift::load_list` for f32/f64
bytecodealliance/wasmtime pull request #9892
Opened 2024-12-23 00:02 UTC by kaivol

Added overrides for `Lower::store_list` and `Lift::load_list` for floating point numbers to reduce overhead when passing or returning `list<f32>` and `list<f64>` to/from components. 

I based this on the respective implementation for integers.

2025-01-02 17:33 UTC, dicej requested changes
Thanks for this!  Looks reasonable to me overall; see my comments inline regarding the details.

2025-01-02 17:33 UTC, dicej commented on crates/wasmtime/src/runtime/component/func/typed.rs
> +                // Note that we're casting a `[u8]` slice to `[$integer]` (with
This paragraph (and the code that follows) refers to `$integer`, but we really care about `$float`, right?  We should rewrite this to talk about floating point numbers instead of integers, e.g. "all `u8` patterns are valid `$float` patterns since `$float` is a IEEE 754 floating point type."

2025-01-02 17:33 UTC, dicej commented on crates/wasmtime/src/runtime/component/func/typed.rs
> +                // The canonical ABI requires that everything is aligned to its
Again, these comments should be updated to discuss floating point types rather than integer types.

2025-01-02 17:33 UTC, dicej commented on crates/wasmtime/src/runtime/component/func/typed.rs
> +                let (before, middle, end) = unsafe { dst.align_to_mut::<$integer>() };
```suggestion
                let (before, middle, end) = unsafe { dst.align_to_mut::<$float>() };
```

Presumably the alignment of e.g. `f32` and `u32` should be the same, but we might as well be precise here (and in similar code below).

2025-01-12 22:07 UTC, kaivol commented
Thanks for the review!
I'm a bit busy at the moment but I'll look into it when i find some time.

2025-03-26 13:33 UTC, kaivol commented on crates/wasmtime/src/runtime/component/func/typed.rs
> +                let (before, middle, end) = unsafe { dst.align_to_mut::<$integer>() };
The reason I used integer types and `align_to[_mut]::<$integer>` was to handle endianness correctly.
I felt like using `align_to[_mut]::<$float>` and thereby transmuting the component's memory to `$float` is incorrect, because (in my understanding) `$float` represents floating point numbers in native endianness, while `dst` is a slice of floating point numbers with little-endian byte-order. 

Therefore, I thought using `$float` for floating point numbers with different endianess would also cause confusion, in particular when converting endianess. 

I also considered using only accordingly aligned bytes (e.g. `[u8; 4]`) for the memory of the component, but I was unsure if that would enable the same optimizations. 
Is there any easy (built-in) way to benchmark Wasmtime in specific scenarios?

Let me know what you think.

2025-03-27 14:34 UTC, kaivol commented
I modified the code to work with byte slices (`[u8]`) when referring to the component's memory. I think this is the best way to show which variables are host and which are component memory. 

I also got rid of the `unsafe` blocks, without compromising on performance (at least in my experiments).

Let me know if the code looks good, and if further comments would help clarify it.

2025-03-27 16:47 UTC, dicej approved these changes
Thanks!

2025-03-27 16:56 UTC, dicej commented on crates/wasmtime/src/runtime/component/func/typed.rs
> +use std::iter;
```suggestion
use core::iter;
```

That should fix https://github.com/bytecodealliance/wasmtime/actions/runs/14112166505/job/39533533593

2025-03-27 21:37 UTC, dicej commented
One last thing to make CI happy (I hope): please run `cargo fmt` and push the result.

2025-03-27 22:45 UTC, merged